utils::globalVariables(c(
  "MOE", "Q", "Q_df", "Q_pval", "Qj", "Qpval", "SNP", "a", "aes",
  "arrange", "attr_list", "b",
  "beta.exposure", "beta.outcome", "bind_rows", "category", "desc", "eaf.exposure",
  "eaf.outcome", "effect", "effect_allele.exposure", "effect_allele.outcome",
  "element_blank", "element_line", "element_text", "expand_limits", "exposure",
  "facet_grid", "gather", "geom_abline", "geom_line", "geom_point", "geom_segment",
  "geom_text", "ggplot", "ggplotGrob", "grid.draw", "grid.newpage", "gtable_matrix",
  "heterogeneity_test", "id.exposure", "id.outcome", "keep", "knit", "knit2html", "labs",
  "left_join", "lo", "lo_ci", "melt", "method", "method2", "mr_keep", "mr_keep.outcome",
  "mr_mode_internal", "n", "nsnp", "nsnp_removed", "obj", "other_allele.exposure",
  "other_allele.outcome", "out", "outcome", "outcome2", "outlier_filtered", "p",
  "pdf_document", "predict", "proxy_snp.outcome", "pval", "pval.exposure",
  "pval.outcome", "r2_ratio", "render", "rsq1", "rsq2", "rsq_emp", "samplesize",
  "scale_x_log10", "scale_y_log10", "se", "se.exposure", "se.outcome", "steiger_dir",
  "steiger_filtered", "theme", "theme_bw", "tibble", "tot", "type", "unit", "up", "up_ci",
  "use_by_default", "value", "vgu", "vgx", "word_document",
  "complete.cases", ".", "eaf", "id", "l2", "l2.x", "n1", "n2", "rsid", "z",
  "orig_SNP"
))
